version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    env_file:
      - .env
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bienvieillir
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db_dump:/docker-entrypoint-initdb.d

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=db
        - MYSQL_ROOT_PASSWORD=root
      ports:
        - "8081:80"
      depends_on:
        - db

  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8082:1080"
      - "8083:1025"